[package]
name = "ratchet-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
async-trait = "0.1"
ratchet-a2a = { workspace = true }

[dev-dependencies]
tempfile.workspace = true
